add: support lsp-pyright including venvs
radian-software/radian pull request #496
Opened 2022-04-03 21:47 UTC by hrehfeld

using `radian--python-find-virtualenv` to set exec-path and `lsp-pyright-extra-paths` in `python-mode-hook`

2022-04-03 21:49 UTC, hrehfeld commented
Maybe we should one of `lsp-python-ms` or `lsp-pyrigh` into `radian-disabled-packages` by default?

2022-04-10 22:22 UTC, raxod502 requested changes

2022-04-10 22:22 UTC, raxod502 commented on emacs/radian.el
> +      )))
```suggestion
        (push (expand-file-name "bin" venv) exec-path)))))
```

2022-04-10 22:22 UTC, raxod502 commented on emacs/radian.el
> +  (defun radian--lsp-pyright-discover-virtualenvs ()
Can we factor this out so that it only runs once when visiting a Python buffer, instead of twice (once for each of the two LSPs)?

2022-04-10 22:22 UTC, raxod502 commented on emacs/radian.el
> +         (python-mode . (lambda () (require 'lsp-pyright))))
I think we can rewrite this as

```elisp
:demand t
:after (:all lsp-mode python-mode)
```

2022-06-01 15:41 UTC, raxod502 reviewed
Hmmm, actually, in the time since you had submitted this, I migrated to Pyright in https://github.com/radian-software/radian/commit/c755184d796f22043b5c36ac7784ec0e3e50df79. Does that implement the same functionality you're adding here?

2022-06-01 15:42 UTC, closed without merging